apiVersion: v1
kind: Service
metadata:
  name: event-api-service
spec:
  type: LoadBalancer
  selector:
    app: event-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http